# Nome da aplicacao
spring.application.name=StyleStock

# Porta do servidor
server.port=8080

# Banco H2 em memoria
spring.datasource.url=jdbc:h2:mem:stylestockdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Console H2 (acesso pelo navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Carrega dados iniciais do arquivo data.sql
spring.sql.init.mode=always
